import { League_Spartan } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const leagueSpartans = League_Spartan({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={leagueSpartans.className}>
      <body>{children}</body>
    </html>
  );
}
